### ISSUE TITLE
`AttributeError: module 'qibo' has no attribute 'K'` when using qibojit-benchmarks with current qibo 

### ISSUE THREAD

**Issue by migueldiascosta** [qiboteam/qibojit-benchmarks#44]
```
Traceback (most recent call last):
  File "qibojit-benchmarks/main.py", line 59, in <module>
    circuit_benchmark(**args)
  File "qibojit-benchmarks/benchmarks/scripts.py", line 33, in circuit_benchmark
    platform=qibo.K.get_platform(),
AttributeError: module 'qibo' has no attribute 'K'
```

I guess qibojit-benchmarks/main.py needs an update similar to https://github.com/qiboteam/qibo/commit/12d44da21c8c2219de2a32a97e09562fb8b4b642 after changes in qibo

**Comment by scarrazza** [comment]
@BrunoLiegiBastonLiegi could you please have a quick look at this?

**Comment by BrunoLiegiBastonLiegi** [comment]
I just opened #46 that should fix this.
